apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-04-16T15:26:37Z"
    generation: 1
    labels:
      app: toystore
    name: toystore
    namespace: default
    resourceVersion: "49494"
    uid: 0aee7fff-8d4a-4b57-b308-fe71f19ec512
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: toystore
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: toystore
      spec:
        containers:
        - image: donnajose/toystore-project:1.0.0
          imagePullPolicy: IfNotPresent
          name: toystore-project
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-04-16T15:26:37Z"
      lastUpdateTime: "2025-04-16T15:26:50Z"
      message: ReplicaSet "toystore-6547f698c7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-04-16T16:00:57Z"
      lastUpdateTime: "2025-04-16T16:00:57Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
