# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


pool:
  vmImage: ubuntu-latest
# stagees:
#   stage: Build
#   displayName: 'Build Stage'
#   jobs:
#         - job: Build Job
#           steps:
#             - task: JavaToolInstaller@0
#               inputs:
#                 versionSpec: '17'
#                 jdkArchitectureOption: x64
#                 jdkSourceOption: PreInstalled
#             - task: Maven@1
#               inputs:
#                 mavenPomFile: 'pom.xml'
#                 goals: 'clean compile' 
stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build and Package Java App'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - bash: echo $(branch_name)
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: PreInstalled
            displayName: 'Set up Java 17'

          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              #options: '-Xmx1024m'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
            displayName: 'Build with Maven'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'target'
              ArtifactName: 'java-app'
              publishLocation: 'Container'
            displayName: 'Publish Build Artifacts'
          - bash: echo $(Build.SourceBranchName) ABC  
  - stage: Dev
    displayName : Dev Staging
    condition: |
      and
      (
        succeeded(),
        eq(variables['Build.SourceBranchName'], 'master')
      )
    jobs:
      - job: DevJob
        displayName: Dev job  
  - stage: Test
    displayName : Test Staging
    condition: |
      and
      (
        succeeded(),
        eq(variables['Build.SourceBranchName'], 'master')
      )
    jobs:
      - job: Test
        displayName: Dev job        