apiVersion: apps/v1
kind: Deployment
metadata:
  name: toystore-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toystore-app
  template:
    metadata:
      labels:
        app: toystore-app
    spec:
      containers:
        - name: toystore-app
          image: donnajose/toystore-project:1.0.0 # Replace this!
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/toystoredb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "com.mysql.cj.jdbc.Driver"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.MySQLDialect"

---
apiVersion: v1
kind: Service
metadata:
  name: toystore-app
spec:
  selector:
    app: toystore-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer